_target_: src.models.caum.caum_module.CAUMModule

# news encoder 
pretrained_word_embeddings_path: null 
pretrained_entity_embeddings_path: null 
word_embedding_dim: ${datamodule.word_embedding_dim}
entity_embedding_dim: ${datamodule.entity_embedding_dim}
category_embedding_dim: 100
news_vector_dim: 400
num_categories: 304
num_attention_heads: 20
query_vector_dim: 200
dropout_probability: 0.2

# user encoder
num_filters: 400
dense_att_hidden_dim1: 400
dense_att_hidden_dim2: 256
user_vector_dim: 400

# evaluation
num_polit_classes: null
num_sent_classes: 4

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00001
