_target_: src.models.dkn.dkn_module.DKNModule

# news encoder
pretrained_word_embeddings_path: null 
pretrained_entity_embeddings_path: null 
word_embedding_dim: ${datamodule.word_embedding_dim}
entity_embedding_dim: ${datamodule.entity_embedding_dim}
num_filters: 100
window_sizes: [1, 2, 3, 4]
use_context: True

# user encoder
hidden_dim_dnn: 16

# evaluation
num_topics: null
num_polit_classes: null
num_sent_classes: 4

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00001
