_target_: src.models.mins.mins_module.MINSModule

# news encoder 
dataset_attributes: ['title', 'abstract', 'category']
pretrained_word_embeddings_path: null 
word_embedding_dim: ${datamodule.word_embedding_dim}
category_embedding_dim: 100
num_categories: 304
num_attention_heads: 15
query_vector_dim: 200
dropout_probability: 0.2

# user encoder
num_filters: 300
num_gru_channels: 6

# evaluation
num_polit_classes: null
num_sent_classes: 4

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00001
