_target_: src.datamodules.nemig_datamodule.NemigDataModule

seed: ${seed}

# Dataset language
lang: null

# KG type
kg_type: 'entities'

# File names and paths
data_dir: ${paths.data_dir}
word_embeddings_dirname: glove
word_embeddings_fpath: 'vectors.txt'
entity_embeddings_filename: 'entity_embedding.vec'

id2index_filenames:
  uid2index: 'uid2index.tsv'
  categ2index: 'categ2index.tsv'
  politic2index: 'politic2index.tsv'
  sentiment2index: 'sentiment2index.tsv'
  word2index: 'word2index.tsv'
  entity2index: 'entity2index.tsv'

word_embedding_dim: 300
entity_embedding_dim: 100

neg_sampling_ratio: 4

max_title_length: 30
max_abstract_length: 50
max_history_length: 10

# Datamodule parameters
batch_size: 4
num_workers: 0
pin_memory: True
drop_last: False 
